version: 2
jobs:
  build:
    docker:
      - image: circleci/node:10
    working_directory: ~/student-debt-campaign
    steps:
      - checkout
      - run: yarn install

      # create .env.production
      # needed by dotenv to work correctly
      - run: touch .env.production
      - run: echo "GOOGLE_ANALYTICS_TRACKING_ID=$GOOGLE_ANALYTICS_TRACKING_ID" >> .env.production
      - run: echo "MAILCHIMP_ENDPOINT=$MAILCHIMP_ENDPOINT" >> .env.production
      - run: echo "MAILCHIMP_GROUP_ID=$MAILCHIMP_GROUP_ID" >> .env.production
      - run: echo "SITE_URL=$SITE_URL" >> .env.production

      # build
      - run: NODE_ENV=production yarn build

      # keep build output for deploy step
      - persist_to_workspace:
          root: ~/student-debt-campaign
          paths:
            - public

  deploy:
    docker:
      - image: circleci/python:2.7-jessie
    working_directory: ~/student-debt-campaign
    steps:
      - attach_workspace:
          at: ~/student-debt-campaign

      - run: sudo pip install awscli
      - run: aws s3 sync public s3://strikestudentdebt.org --delete

workflows:
  version: 2
  build-deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: master
